name: "boywithkeyboard/publisher"
description: "An opinionated, production-ready release manager."
inputs:
  tag:
    description: "The GitHub access token to use for creating a new release."
    required: false
    default: "<tag>"
  draft:
    description: "Create the new release as a draft."
    required: false
    default: "false"
  prerelease:
    description: "Create the new release as a pre-release."
    required: false
    default: "false"
  token:
    description: "The access token to use for creating the new release."
    required: false
    default: "${{ github.token }}"
branding:
  icon: "tag"
  color: "gray-dark"
runs:
  using: "node20"
  main: "build/index.js"
